name: PR Workflow

on:
  pull_request:
    branches:
      - main  # adjust to your main branch name

jobs:
  send-pr-details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send PR details to Flask API
        run: |
          PR_DETAILS=$(echo '{"diff_url": "${{ github.event.pull_request.diff_url }}", "number": "${{ github.event.pull_request.number }}", "repo": "${{ github.event.repository.name }}", "owner": "${{ github.event.pull_request.user.login }}", "github_token": "${{ secrets.GITHUB_TOKEN }}", "head_sha": "${{ github.event.pull_request.head.sha }}"}')
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$PR_DETAILS" \
            https://f1cb-103-72-193-1.ngrok-free.app/workflows
