name: Send PR and Check for "hello"

on:
  pull_request:
    branches: 
      - main

jobs:
  send_pr_and_check_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR Diff
        id: get_pr_diff
        run: |
          PR_DIFF=$(curl -s "${{ github.event.pull_request.diff_url }}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}")
          echo "PR_DIFF<<EOF" >> $GITHUB_ENV
          echo "$PR_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send PR information to FlaskAPI
        id: send_pr_info
        run: |
          API_URL="https://chatty-nails-reply.loca.lt/workflows"
          PR_DETAILS=$(echo "{\"diff_url\": \"${{ github.event.pull_request.diff_url }}\", \"number\": \"${{ github.event.pull_request.number }}\", \"repo\": \"${{ github.event.repository.name }}\", \"owner\": \"${{ github.event.pull_request.user.login }}\", \"github_token\": \"${{ secrets.GITHUB_TOKEN }}\", \"head_sha\": \"${{ github.event.pull_request.head.sha }}\"}")
          response=$(curl -X POST -H "Content-Type: application/json" -d "$PR_DETAILS" "$API_URL")
          echo "response=$response" >> $GITHUB_ENV

      - name: Wait for FlaskAPI response
        id: wait_for_response
        run: echo "Waiting for FlaskAPI response..."

      - name: Print response
        run: echo "The response is ${{ env.response }}"

      
