name: PR Workflow

on:
  pull_request:
    branches:
      - main  # adjust to your main branch name

jobs:
  send-pr-details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send PR details to Flask API
        run: |
          PR_DETAILS=$(echo '{"diff_url": "${{ github.event.pull_request.diff_url }}", "number": "${{ github.event.pull_request.number }}", "owner": "${{ github.event.pull_request.user.login }}", "github_token": "${{ secrets.GITHUB_TOKEN }}"}')
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$PR_DETAILS" \
            https://e43b-2001-df4-2a00-6-7440-3853-461b-e549.ngrok-free.app/workflows
