name: Send PR and Check for "hello msg"

on:
  pull_request:
    branches:
      - main

jobs:
  send_pr_and_check_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install axios
        run: npm install axios

      - name: Get PR Diff
        id: get_pr_diff
        run: |
          echo "Fetching PR diff..."
          curl -s "${{ github.event.pull_request.diff_url }}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" > pr_diff.txt
          echo "PR diff content fetched."

      - name: Perform POST Request to Flask API
        id: post_api
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const axios = require('axios');
            const core = require('@actions/core'); // Ensure core is required
            const apiUrl = 'https://sad-dots-rule.loca.lt/workflows';
            const diffUrl = '${{ github.event.pull_request.diff_url }}';
            const number = '${{ github.event.pull_request.number }}';
            const repo = '${{ github.event.repository.name }}';
            const owner = '${{ github.event.pull_request.user.login }}';
            const githubToken = '${{ secrets.GITHUB_TOKEN }}';
            const headSha = '${{ github.event.pull_request.head.sha }}';

            const requestData = {
              diff_url: diffUrl,
              number: number,
              repo: repo,
              owner: owner,
              github_token: githubToken,
              head_sha: headSha
            };

            try {
              const response = await axios.post(apiUrl, requestData, {
                headers: {
                  'Content-Type': 'application/json'
                }
              });
              const data = response.data;

              // Handle API response
              if (data.status === 'error') {
                core.setFailed(`API Error: ${data.message}`);
              } else if (data.status === 'warning') {
                if (Array.isArray(data.warning_messages)) {
                  // Iterate over the list and issue warnings
                  data.warning_messages.forEach(message => {
                    core.warning(`Warning: ${message}`);
                  });
                } else {
                  core.warning('Unknown warning format');
                }
              } else {
                console.log('API response is OK.');
              }
            } catch (error) {
              core.setFailed(`API request failed: ${error.message}`);
            }
