name: PR Workflow

on:
  pull_request:
    branches:
      - main  # adjust to your main branch name

jobs:
  send-pr-details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send PR details to Flask API
        run: |
          PR_DETAILS=$(echo '${{ toJson(github.event.pull_request) }}')
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$PR_DETAILS" \
            https://007b-103-72-193-1.ngrok-free.app/workflows
