name: Send PR and Check for "hello"

on:
  pull_request:
    branches: 
      - main

jobs:
  send_pr_and_check_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send PR information to FlaskAPI
        id: send_pr_info
        run: |
          API_URL="https://10.6.56.42:5050/workflows"
          PR_DIFF="${{ steps.get_pr_diff.outputs.diff_content }}"
          PR_DETAILS=$(echo '{"diff_url": "${{ github.event.pull_request.diff_url }}", "number": "${{ github.event.pull_request.number }}", "repo": "${{ github.event.repository.name }}", "owner": "${{ github.event.pull_request.user.login }}", "github_token": "${{ secrets.GITHUB_TOKEN }}", "head_sha": "${{ github.event.pull_request.head.sha }}"}')
          response=$(curl -X POST -H "Content-Type: application/json" -d "$PR_DETAILS" "$API_URL")
          echo "response=$response" >> $GITHUB_OUTPUT

      - name: Wait for FlaskAPI response
        id: wait_for_response
        run: echo "Waiting for FlaskAPI response..."

      - name: Print response
        run: echo "The response is ${{ steps.send_pr_info.outputs.response }}"
        
      - name: Raise warning if secrets found
        if: steps.send_pr_info.outputs.response == 'action_required'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Check Hello Content in PR Diff',
              head_sha: context.sha,
              conclusion: 'neutral',
              status: 'completed',
              started_at: new Date().toISOString(),
              completed_at: new Date().toISOString(),
              output: {
                title: 'Warning: PR diff contains "hello"',
                summary: 'Please review the PR as it contains secrets in the diff content.',
              }
            });
