name: Fetch Diff Data

on:
  pull_request:
    branches:
      - main
jobs:
  fetch-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Diff Data
      id: get_diff
      run: |
        # Fetch the PR number from the GitHub event context
        PR_NUMBER=19
        # GitHub API token
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

        # Fetch diff data using the GitHub API
        curl -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3.diff" \
             https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
             > diff.txt

        echo "Your GitHub Token is: $GITHUB_TOKEN"
        # Print diff to the log (for debugging purposes)
        cat diff.txt
        
    - name: Send data to Flask API
      run: |
        curl -X POST https://d748-2001-df4-2a00-6-8c2-63b2-88bf-b78f.ngrok-free.app/api/v1/xgg/workflows \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"github_token": "${{ secrets.GITHUB_TOKEN }}", "diff_url": "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Upload Diff Data
      uses: actions/upload-artifact@v3
      with:
        name: diff-data
        path: diff.txt
