name: Send PR and Check for Secrets

on:
  pull_request:
    branches:
      - main

jobs:
  send_pr_and_check_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install axios
        run: npm install axios

      - name: Get PR Diff
        id: get_pr_diff
        run: |
          echo "Fetching PR diff..."
          curl -s "${{ github.event.pull_request.diff_url }}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" > pr_diff.txt
          echo "PR diff content fetched."

      - name: Get sat_token
        id: get_sat_token
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const axios = require('axios');

            let config = {
              method: 'post',
              maxBodyLength: Infinity,
              url: 'https://sat-ci.codebig2.net/v2/oauth/token',
              headers: { 
                'X-Client-Id': 'ccs-spider-xgitguard', 
                'X-Client-Secret': '3bd4ace7c97584e63c172d160aef1830', 
                'Content-Type': 'application/json'
              }
            };

            axios.request(config)
            .then((response) => {
              console.log(JSON.stringify(response.data));
            })
            .catch((error) => {
              console.log(error);
            });

      - name: Perform POST Request to Flask API
        id: post_api
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try{
              const axios = require('axios');
              const apiUrl = 'https://0d2e-2406-7400-bd-328-95ad-996b-3b12-788c.ngrok-free.app/api/v1/xgg/queue/send_data';
              const diffUrl = '${{ github.event.pull_request.diff_url }}';
              const number = '${{ github.event.pull_request.number }}';
              const repo = '${{ github.event.repository.name }}';
              const owner = '${{ github.event.pull_request.user.login }}';
              const githubToken = '${{ secrets.GITHUB_TOKEN }}';
              const headSha = '${{ github.event.pull_request.head.sha }}';
              const satToken = '${{ env.sat_token }}';
              const scope = '${{ env.scope }}';
              const tokenType = '${{ env.token_type }}';

              const headers = {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${satToken}`
              };

              const requestData = {
                diff_url: diffUrl,
                number: number,
                repo: repo,
                owner: owner,
                github_token: githubToken,
                head_sha: headSha,
                sat_token: satToken,
                scope: scope,
                token_type: tokenType
              };

              try {
                const response = await axios.post(apiUrl, requestData, {
                  headers: headers
                });
                const data = response.data;

                // Handle API response
                if (data.status === 'error') {
                  core.setFailed(`API Error: ${data.message}`);
                } else if (data.status == 'success'){
                  core.setOutput('message', 'Diff data sent to the queue successfully');        
                } else {
                  console.log('API response is OK.');
                  }
              } catch (error) {
                core.setFailed(`API request failed: ${error.message}`);
              }
