name: Example Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read    # Read access to repository contents
  pull-requests: read  # Read access to pull requests
  actions: write    # Write access to actions (if needed)

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch PR Diff
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=19
        REPO=${{ github.repository }}
        
        curl -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3.diff" \
             "https://api.github.com/repos/${REPO}/pulls/${PR_NUMBER}/diff" > pr_diff.txt

        cat pr_diff.txt
